gray-design/config/routes.rb
Rails.application.routes.draw do
  resources :metrics

  root :to => "home#index"
  get "warnings/" => "home#warnings"
  get "lists/" => "home#lists"
end

gray-design/app/models/metric.rb
class Metric < ActiveRecord::Base
  # Publish to Redis on changes.
  # after_create { |metric| metric.message 'create' }
  after_update { |metric| metric.message 'update' }
  # after_destroy { |metric| metric.message 'descroy' }

  # Publish an action to Redis
  #
  # action - String representing the action.
  #
  # Example:
  #  message('create')
  #
  # Returns nothing.
  def message(action)
    msg = {
      :resource => 'metrics',
      :action => action,
      :name => self.name,
      :description => self.description,
      :value => self.value,
      :id => self.id,
    }

    begin
      Daemons.call(:multiple => true) do
        $redisSender.publish 'redis-metric-change-downstream', msg.to_json
      end
    rescue
      # Ignore it.
    end
  end
end

gray-design/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

gray-design/app/controllers/home_controller.rb
class HomeController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  layout "application"

  def index
    @metrics = Metric.all
  end

  def warnings
  end

end

gray-design/app/controllers/metrics_controller.rb
class MetricsController < ApplicationController
  before_action :set_metric, only: [:show, :edit, :update, :destroy]

  # GET /metrics
  # GET /metrics.json
  def index
    data = []
    Metric.all[0,5].each do |metric|
      data << {
        'name' => metric.name,
        'description' => metric.description,
        'value' => metric.value,
        'id' => metric.id,
      }
    end
    render :json => data
  end

  # GET /metrics/1
  # GET /metrics/1.json
  def show
  end

  # GET /metrics/new
  def new
    @metric = Metric.new
  end

  # GET /metrics/1/edit
  def edit
  end

  # POST /metrics
  # POST /metrics.json
  def create
    @metric = Metric.new(metric_params)

    respond_to do |format|
      if @metric.save
        format.html { redirect_to @metric, notice: 'Metric was successfully created.' }
        format.json { render action: 'show', status: :created, location: @metric }
      else
        format.html { render action: 'new' }
        format.json { render json: @metric.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /metrics/1
  # PATCH/PUT /metrics/1.json
  def update
    respond_to do |format|
      if @metric.update(metric_params)
        format.html { redirect_to @metric, notice: 'Metric was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @metric.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /metrics/1
  # DELETE /metrics/1.json
  def destroy
    @metric.destroy
    respond_to do |format|
      format.html { redirect_to metrics_url }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_metric
    @metric = Metric.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def metric_params
    params.require(:metric).permit(:name, :description, :value, :active)
  end
end

gray-design/app/helpers/application_helper.rb
module ApplicationHelper
end

gray-design/app/helpers/metrics_helper.rb
module MetricsHelper
end

gray-design/app/views/home/_info_bar.html.haml
%h2 Info
%p Here is some info:
%ul
  %li
    = link_to "Home", :root
  %li
    = link_to "Warnings", "warnings"
  %li
    = link_to "Lists", "lists"

gray-design/app/views/home/index.html.haml
%div#content.container
  %div#main-content.container

    %div.row

    %div.col-md-9{"ng-controller" => "metricsListCtrl as metricsListCtrl"}
      -# %div{"ng-controller" => "metricsListCtrl as metricsListCtrl"}
      %textarea.content-box{:style => "width: 100%; height: 200px;"} {{metricsListCtrl.metrics | json}}
      %h2
        Metrics
        %a.btn.btn-default{"ng-click" => "metricsListCtrl.refresh()"} Refresh

      %div{"ng-cloak" => "", "ng-repeat" => "metric in metricsListCtrl.metrics"}
        %div.content-box{"ng-class" => "{'updated-content-box': metric.updated}"}
          %strong Name:
          %input{:type => "text", "ng-model" => "metric.name", "ng-click" => "metricsListCtrl.markAsDirty(metric)"}
          %strong Description:
          %input{:type => "text", "ng-model" => "metric.description", "ng-click" => "metricsListCtrl.markAsDirty(metric)"}
          %strong Value:
          %input{:type => "text", "ng-model" => "metric.value", "ng-click" => "metricsListCtrl.markAsDirty(metric)"}
          %a.btn.btn-default{"ng-show" => "metric.dirty", "ng-click" => "metricsListCtrl.saveMetric(metric)"} Save

      %h2 Main
      %div.content-box
        %p This is a test. Test.

        %h2 Tests
        %p
          Have a look at the
          = link_to "Warnings", "warnings"
          and the
          = link_to "Lists", "lists"

        %h2 About This Site
        %p
          "Lorem ipsum dolor sit amet, consectetaur adipisicing elit, sed do
          eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad
          minim veniam, quis nostrud exercitation ullamco laboris nisi ut
          aliquip ex ea commodo consequat. Duis aute irure dolor in
          reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla
          pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
          culpa qui officia deserunt mollit anim id est laborum."

          Sed ut perspiciatis unde omnis iste natus error sit voluptatem
          accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae
          ab illo inventore veritatis et quasi architecto beatae vitae dicta
          sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit
          aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos
          qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui
          dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed
          quia non numquam eius modi tempora incidunt ut labore et dolore magnam
          aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum
          exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex
          ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in
          ea voluptate velit esse quam nihil molestiae consequatur, vel illum
          qui dolorem eum fugiat quo voluptas nulla pariatur?

          At vero eos et accusamus et iusto odio dignissimos ducimus qui
          blanditiis praesentium voluptatum deleniti atque corrupti quos dolores
          et quas molestias excepturi sint occaecati cupiditate non provident,
          similique sunt in culpa qui officia deserunt mollitia animi, id est
          laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita
          distinctio. Nam libero tempore, cum soluta nobis est eligendi optio
          cumque nihil impedit quo minus id quod maxime placeat facere possimus,
          omnis voluptas assumenda est, omnis dolor repellendus. Temporibus


    %div.col-md-3
      .content-box.info-box
        = render 'info_bar'

gray-design/app/views/home/lists.html.haml
%div#content.container
  %div#main-content.container

    %div.row

    %div.col-md-9
      .content-box
        %h2 Main
        %pThis is a test.

        %h2 Horizontal List
        %ul.horizontal-list
          %li List item
          %li List item
          %li List item
          %li List item

        %h2 Inline List
        %ul.inline-list
          %li List item
          %li List item
          %li List item
          %li List item

        %h2 Tag Cloud
        %ul.tag-cloud
          %li.xs red
          %li.xxs gree
          %li.xxl blue
          %li.xl yellow
          %li.l white
          %li.l pink
          %li.s orange
          %li.xxl brown
          %li.xl grey

    %div.col-md-3
      .content-box
        = render 'info_bar'

gray-design/app/views/home/warnings.html.erb
<div id="content" class="container">
  <div id="main-content" class="container">

    <div class="row">

      <div class="col-md-9 content-box">
        <h2>Main</h2>
        <p>This is a test.</p>

        <h2>Warning</h2>
        <div class="warning-element">
          <h3>Warning</h3>
          <p>There have been complications.</p>
        </div>

        <h2>Serious Warning</h2>
        <div class="serious-warning-element">
          <h3>Warning</h3>
          <p>There have been complications.</p>
        </div>

        <h2>Special Warning</h2>
        <div id="special-warning" class="warning-element">
          <h3>Warning</h3>
          <p>Tis is a special warning.</p>
        </div>

        <h2>Warning With Default Border Width</h2>
        <div id="default-border-warning" class="warning-element">
          <h3>Warning</h3>
          <p>Tis is a warning using the default border width.</p>
        </div>

        <h2>Rotated Warning</h2>
        <p><strong>Hint: </strong>Hover over this warning box to rotate it back.</p>
        <div class="rotated-warning-element">
          <h3>Warning</h3>
          <p>This warning is rotated.</p>
        </div>

      </div>

      <div class="col-md-3 content-box">
        <%= render 'info_bar' %>
      </div>

    </div>
  </div>
</div>

gray-design/app/views/layouts/application.html.haml
!!! html
%html{"ng-app" => "metricsApp"}
  %head
    %title
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = csrf_meta_tags

  %body
    %div#header
      %div#main-header-bar.container
        %div#main-header.container

          %div#logo.col-md-1
            %a{:href => "/"} Logo

          %div#main-menu.col-md-5

          %input#menu-toggle{:type => "checkbox"}
          %label#menu-label{:for => "menu-toggle", :onclick => ""}

          %div#main-menu.col-md-6
            %nav{:role => "navigation"}
              %ul
                %li
                  %a{:href => "#"} About
                %li
                  %a{:href => "#"} Company
                %li
                  %a{:href => "#"} How it works
                %li
                  %a{:href => "#"} Contact
    = yield

    %div#footer.container
      %div#footer-content.container
        %div.col-md-12.text-center
          %nav
            %ul
              %li
                %a{:href => "/"} Home
              %li
                %a{:href => "/"} Diverse
              %li
                %a{:href => "/"} Other things
              %li
                %a{:href => "/"} Anything

    = javascript_include_tag "application", "data-turbolinks-track" => true

gray-design/app/views/metrics/_form.html.erb
<%= form_for(@metric) do |f| %>
  <% if @metric.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@metric.errors.count, "error") %> prohibited this metric from being saved:</h2>

      <ul>
      <% @metric.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :value %><br>
    <%= f.number_field :value %>
  </div>
  <div class="field">
    <%= f.label :active %><br>
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

gray-design/app/views/metrics/edit.html.erb
<h1>Editing metric</h1>

<%= render 'form' %>

<%= link_to 'Show', @metric %> |
<%= link_to 'Back', metrics_path %>

gray-design/app/views/metrics/index.html.erb
<h1>Listing metrics</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Value</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @metrics.each do |metric| %>
      <tr>
        <td><%= metric.name %></td>
        <td><%= metric.description %></td>
        <td><%= metric.value %></td>
        <td><%= metric.active %></td>
        <td><%= link_to 'Show', metric %></td>
        <td><%= link_to 'Edit', edit_metric_path(metric) %></td>
        <td><%= link_to 'Destroy', metric, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Metric', new_metric_path %>

gray-design/app/views/metrics/new.html.erb
<h1>New metric</h1>

<%= render 'form' %>

<%= link_to 'Back', metrics_path %>

gray-design/app/views/metrics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @metric.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @metric.description %>
</p>

<p>
  <strong>Value:</strong>
  <%= @metric.value %>
</p>

<p>
  <strong>Active:</strong>
  <%= @metric.active %>
</p>

<%= link_to 'Edit', edit_metric_path(@metric) %> |
<%= link_to 'Back', metrics_path %>